"""rename weight to weight_lb, add program tables

Revision ID: 0b36035b6e36
Revises: 1afae9b75f85
Create Date: 2026-04-05 21:07:52.932913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b36035b6e36'
down_revision = '1afae9b75f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_template_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_lb', sa.Float(), nullable=True))
        batch_op.drop_column('weight')

    op.create_table(
        'programs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('total_weeks', sa.Integer(), nullable=False, server_default='4'),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_table(
        'program_days',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('program_id', sa.Integer(), sa.ForeignKey('programs.id'), nullable=False),
        sa.Column('week_number', sa.Integer(), nullable=False),
        sa.Column('day_order', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('template_id', sa.Integer(), sa.ForeignKey('workout_templates.id'), nullable=True),
        sa.Column('label', sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_days')
    op.drop_table('programs')
    with op.batch_alter_table('workout_template_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=True))
        batch_op.drop_column('weight_lb')

    # ### end Alembic commands ###
