"""add unit to users

Revision ID: 1afae9b75f85
Revises: 445a83d6c5fb
Create Date: 2026-04-05 20:50:59.888130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afae9b75f85'
down_revision = '445a83d6c5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=5), nullable=False, server_default='lb'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
