"""remove_personal_maxes_fix_ai_knowledge_nullable

Revision ID: 6d29d6812665
Revises: a3f7e2c91d04
Create Date: 2026-04-17 20:08:12.029659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d29d6812665'
down_revision = 'a3f7e2c91d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS personal_maxes")
    with op.batch_alter_table('ai_knowledge', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_knowledge', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.execute("""
        CREATE TABLE IF NOT EXISTS personal_maxes (
            id INTEGER NOT NULL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            exercise_name VARCHAR(120) NOT NULL,
            weight_lb FLOAT NOT NULL,
            is_manual BOOLEAN NOT NULL,
            UNIQUE (user_id, exercise_name)
        )
    """)
    # ### end Alembic commands ###
